-- Standard Function

-- DUAL TABLE : 가상테이블 -> 결과확인 테이블

SELECT 1 FROM DUAL;
SELECT 'A' FROM DUAL;
SELECT '가' FROM DUAL;
SELECT 36*24 FROM DUAL;

-- 문자 함수
--CHR( NUMBER ) : ASCII 값을 문자로 변환 A==65
SELECT CHR(65) FROM DUAL;
SELECT CHR(48) FROM DUAL;

-- CONCAT -> 두문자를 합치는것
SELECT CONCAT('HELLO', 'WORLD') FROM DUAL;

SELECT '내 점수는 ' || CHR(65) || '입니다' FROM DUAL;
--"내 점수는 " + CHR(65) + "입니다"

--LPAD(RPAD) : 총칸 수의 빈칸을 지정문자(빈문자)로 채운다.
SELECT LPAD('BBB', 10) FROM DUAL;
SELECT RPAD('BBB', 10) FROM DUAL;
SELECT LPAD('BBB', 10, '-') FROM DUAL;
SELECT LPAD('BBB', 10, '0') FROM DUAL;

--INSTR == indexof "abcde" indexof('b') -> 1, DB는 INDEX 0이 없음
SELECT INSTR('123ABC456DEFABC', 'A') FROM DUAL;
SELECT INSTR('123ABC456DEFABC', 'A', 6) FROM DUAL; -- 시작 INDEX 지정
SELECT INSTR('123ABC456DEFABCABC', 'A', 6, 1) FROM DUAL; -- N번째 INDEX출력
SELECT INSTR('123ABC456DEFABCABC', 'A', 6, 2) FROM DUAL; -- N번째 INDEX출력
SELECT INSTR('123ABC456DEFA', 'X') FROM DUAL;

-- REPLACE : 문자열 치환
SELECT REPLACE('AAAAABCD', 'A') FROM DUAL;
SELECT REPLACE('AAAAABCD', 'A', 'a') FROM DUAL;
SELECT REPLACE('AAAAABCD', 'AA', 'a') FROM DUAL;

-- SUBSTR  java의 경우 "ABCDE" -> substring(1,3) ==> "BC"
SELECT SUBSTR('ABCDE', 3) FROM DUAL;        --3번지부터 끝까지
SELECT SUBSTR('ABCDE', 3, 2) FROM DUAL;     --3번지부터 2문자

-- 숫자
--올림
SELECT CEIL(13.1) FROM DUAL;

--내림
SELECT FLOOR(13.9) FROM DUAL;

--나눈 나머지
SELECT MOD(3,2) FROM DUAL;

--승수 Math.pow()
SELECT POWER(3, 2) FROM DUAL;

--반올림
SELECT ROUND(13.5) FROM DUAL;

-- 부호 1 0 -1
SELECT SIGN(13.4) FROM DUAL;
SELECT SIGN(0) FROM DUAL;
SELECT SIGN(-0.4) FROM DUAL;

--버림(소수)
SELECT TRUNC(123.4567) FROM DUAL;
SELECT TRUNC(123.4567, 2) FROM DUAL;
SELECT TRUNC(123.4567, 1) FROM DUAL;
SELECT TRUNC(123.4567, -1) FROM DUAL;

--변환함수
--TO_CHAR = DATE -> VARCHAR2
SELECT TO_CHAR(SYSDATE) FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD-HH-MI-SS') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH:MI:SS') FROM DUAL;

SELECT TO_CHAR(COL1, 'YYYY/MM/DD HH:MI:SS') FROM TB_DATE;
SELECT TO_CHAR(10000000, '$999,999,999') FROM DUAL;

-- TO_DATE = VARCHAR2 -> DATE
SELECT TO_DATE('20210909') FROM DUAL;
SELECT TO_DATE('20210909', 'YYYYMMDD') FROM DUAL;

-- TO_NUMBER = VARCHAR2 -> NUMBER       Integer.parseint("1000")
SELECT TO_NUMBER('12345') + 45 FROM DUAL;
SELECT '12345' + 45 FROM DUAL; -- 자동연산되기는 하나 올바른 표현이 아님

--LAST_DAY
SELECT LAST_DAY('21/09/09') FROM DUAL;

SELECT LAST_DAY(TO_DATE('211012','YYMMDD')) FROM DUAL;

SELECT SYSDATE FROM DUAL;


--년도, 월, 일, 시, 분, 초 
SELECT SYSDATE,
    EXTRACT(YEAR FROM SYSDATE),
    EXTRACT(MONTH FROM SYSDATE),
    EXTRACT(DAY FROM SYSDATE),
    EXTRACT(HOUR FROM CAST(SYSDATE AS TIMESTAMP)),
    EXTRACT(MINUTE FROM CAST(SYSDATE AS TIMESTAMP)),
    EXTRACT(SECOND FROM CAST(SYSDATE AS TIMESTAMP))
FROM DUAL;

